template-file-path: wordpress.json
parameters:
  KeyName: us-east-1
  SSHLocation: 0.0.0.0/0
  DBPassword: '****'
  DBName: wordpressdb
  DBUser: '****'
  DBRootPassword: '****'
  InstanceType: t2.small
tags: {}
